name: Tests

on:
   pull_request:
   push:
   workflow_call:

jobs:
   cypress-run:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - name: Install Node.js
           uses: actions/setup-node@v3
           with:
              node-version: 20
         - uses: pnpm/action-setup@v2
           name: Install pnpm
           with:
              version: 8
              run_install: true
         - name: Test with Cypress
           uses: cypress-io/github-action@v5
           with:
              env: CI=true
              component: true
              install: true
              browser: chrome
